config/routes.rb
PivotalOverview::Application.routes.draw do

  root :to => "root_page#index"

  resources :root_page, :print

  resources :projects do
    resources :stories
  end

end

app/models/project_data.rb
class ProjectData < PivotalTracker::Project

  def self.find_all_projects

    if Token.set? then
      projects = PivotalTracker::Project.all
    end

    projects
  end

  def self.find_project (id)
    if Token.set? then
      project = PivotalTracker::Project.find(id)
    end

    project
  end

  def self.find_all_stories(project, states=["unscheduled", "unstarted", "started", "finished", "delivered", "accepted", "rejected"])
    if Token.set? then
      stories = project.stories.all(:current_state => states, :story_type => ['feature', 'bug', 'chore'] )
    end

    stories
  end

  def self.find_story(project, id)
    if Token.set? then
      story = project.stories.find(id)
    end

    story
  end

  def self.find_tasks(story)
    if Token.set? then
      tasks = story.tasks.all
    end

    tasks
  end

  def self.find_notes(story)
    if Token.set? then
      notes = story.notes.all
    end

    notes
  end


end

app/models/token.rb
class Token
  @token=nil   #N.B. Class Instance Variable

  def self.set?
    PivotalTracker::Client.token = @token
    !@token.blank?
  end

  def self.update_token( new_token)
    @token = new_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :get_filtered_stories, :get_current_year

  def get_filtered_stories(project)
    filter = params[:state]  || ["unscheduled", "unstarted"]
    ProjectData.find_all_stories(project, filter )
  end

  def get_current_year
    date=Date.today
    date.year
  end

  def get_pivotal_token
    @token = params[:token]

    unless @token.nil?
      Token.update_token(@token)
      cookies.permanent[:token] = @token
      logger.debug "Retrieve Pivotal token #{@token} from page submission and store in cookie"
    end

    unless cookies[:token].nil?
      Token.update_token(cookies[:token])
      logger.debug ("Using token #{cookies[:token]} from the session cookie")
    end
  end

end

app/controllers/print_controller.rb
require 'story_extensions'
require 'pdf_library'

class PrintController < ApplicationController

  @current_filter = @state_selection

  def index
    @state_selection = ["unscheduled", "unstarted", "started", "finished", "delivered", "accepted", "rejected"]

    get_pivotal_token

    @projects = ProjectData.find_all_projects
  end

  def create
    print_stories = params[:story]
    @stories=[]

    get_pivotal_token

    # Extract the project id and story id from the concatenated params has we created
    print_stories.each do |s|
      str = s.split
      project = ProjectData.find_project Integer(str[0])
      @stories.push ProjectData.find_story(project,Integer(str[1]))
    end

    pdf = PDF::Generator.new(@stories)
    file = pdf.write_to

    send_file file.path, :type=>"application/pdf" unless file.nil?

    #file.unlink  # deletes the temp file
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    get_pivotal_token
    @projects = ProjectData.find_all_projects
  end

  def show
    get_pivotal_token
    @project = ProjectData.find_project(Integer(params[:id]))
    logger.debug("Project #{params[:id]}")
  end
end

app/controllers/root_page_controller.rb
class RootPageController < ApplicationController
  def index

  end

  def show

  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    get_pivotal_token
    project = ProjectData.find_project(Integer(params[:project_id]))
    @stories = ProjectData.find_all_stories(project)
  end

  def show
    get_pivotal_token
    project = ProjectData.find_project(Integer(params[:project_id]))
    @story = ProjectData.find_story(project, Integer(params[:id]))
    @tasks =  ProjectData.find_tasks(@story)
    @notes = ProjectData.find_notes(@story)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/print_helper.rb
module PrintHelper

end

app/helpers/root_page_helper.rb
module RootPageHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PivotalOverview</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="main_border clearfix">

  <div class="page_header clearfix">
    <div class="page_banner"></div>
    <div class="token">
      <div class="token_input">
        <%= form_tag(:controller, :method => "get") do %>
            <%= label_tag(:token, "Enter your Pivotal Tracker Token:") %>
            <%= text_field_tag(:token, nil, :class => 'rounded-corners') %>
            <%= submit_tag("Submit") %>
        <% end %>
      </div>
      <div class="close_button">X</div>
    </div>
  </div>



  <%= yield %>

  <div class="footer">
    (c) 2012 - <%= get_current_year %>  - All rights reserved - use of this site comes with no warranty
  </div>

</div>

</body>
</html>

app/views/print/_story.erb
<div class="story">
  <%= check_box_tag 'story[]', [project_id, story.id],
                    (params[:stories] || {}).include?(story.id) %>
  <%= link_to story.name, project_story_url(:project_id => project_id, :id => story.id), :class => 'printrows' %>
</div>

app/views/print/create.html.erb
<H1> PDF Generated</H1>

<%= @stories.inspect %>

app/views/print/index.erb
<div class="print_display_opts">
  <%= form_tag({:controller => :print, :action => "index"}, :method => "get", :class => "state_chooser") do %>

      <div class="form_row">
        <label for="state[]">States:</label>
        <% @state_selection.each do |s| %>
            <br><%= check_box_tag 'state[]', s, (params[:states] || {}).include?(s) %>
            <%= s %>
        <% end %>
      </div>

      <div class="print_filter_button">
        <%= submit_tag("Filter Stories", :class => 'print_filter_button rounded_button') %>
      </div>
  <% end %>
</div>

<%= form_tag do %>
    <%= submit_tag("Print selected items", :class => 'rounded_button print_button') %>
    <div class="projects">
      <% if !Token.set? %>
          <div id="error"></div>
          Please set your Pivotal tracker token in order to access project data.
          <br/>Log in to your account at
          <a href="http://www.pivotaltracker.com">Pivotal Tracker</a> site and you will find it under the profile menu. </div>
      <% elsif @projects.nil? %>
          <div id="error">No project data could be retrieved from Pivotal Tracker</div>
      <% else %>
          <% @projects.each do |p| %>
              <% stories = get_filtered_stories(p) %>
              <% unless stories.nil? %>
                  <div class="project">
                    <div class="header">
                      <%= p.name %>
                    </div>
                    <div class="stories">
                      <%= render :partial => "story", :collection => stories, :locals => {:project_id => p.id} %>
                    </div>
                  </div>
              <% end %>
          <% end %>
      <% end %>
      </div>
<% end %>

app/views/projects/index.erb
<% @projects.each do |p| %>
    <%= p.name %> <br>
<% end %>

app/views/projects/show.erb
<h1><%= @project.name %></h1>

app/views/root_page/index.erb
<h1>Pivotal Overview - Main Menu</h1>
<p>Choose where to go from here</p>

<div class="Links_table">
  <div class="link"><%= link_to "Print Story cards", print_index_path %>  </div>
</div>

app/views/root_page/show.erb
<h1>Pivotal Overview - Main Menu</h1>
<p>Choose where to go from here</p>

<div class="Links_table">
  <div class="link"><%= link_to "Print Story cards", print_index_path %>  </div>
</div>

app/views/stories/index.erb
<% @stories.each do |story| %>
    <%=  story.name %><br>
<% end %>

app/views/stories/show.erb
<div class="storycard">
  <h1><%= @story.name %></h1>

  <div class="storydescription"></div>
  <%= @story.description %>

  <ul>

    <% @tasks.each do |t| %>
        <li>
          <div class=<%= t.complete %>>

            <%= t.description %>
          </div>
        </li>
    <% end %>
  </ul>

  <ul>

    <% @notes.each do |n| %>
        <li>
            <%= n.text %>
        </li>
    <% end %>
  </ul>

</div>